### ISSUE TITLE
Player doesn't work when third-party cookies are blocked

### ISSUE THREAD

**Issue by lutangar** [apivideo/player-sdk#1]
When third party cookies are blocked, the player doesn't work when **embedded** on a page.
Either using the `player-sdk` or the iframe URL, the same error occurs.

Error in Chrome :
```
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at oc (https://embed.api.video/player.238c9e4.js:2:458345)
    at lc.value (https://embed.api.video/player.238c9e4.js:2:460299)
    at new lc (https://embed.api.video/player.238c9e4.js:2:468024)
    at Object.handleSource (https://embed.api.video/player.238c9e4.js:2:469227)
    at a.r.setSource (https://embed.api.video/player.238c9e4.js:2:82860)
    at u.<anonymous> (https://embed.api.video/player.238c9e4.js:2:192777)
    at u.e.ready (https://embed.api.video/player.238c9e4.js:2:23542)
    at u.e.techCall_ (https://embed.api.video/player.238c9e4.js:2:192576)
    at u.<anonymous> (https://embed.api.video/player.238c9e4.js:2:201254)
    at u.e.ready (https://embed.api.video/player.238c9e4.js:2:23542)
```

Third party cookies are well known practices in the advertising industry, I wouldn't recommend to rely on it for the player to be functional. Or at least do something to fail silently and not break everything else.

In Chrome the **Block third-party cookies** option is described as follow :
> When on, sites can’t use your browsing activity across different sites to personalize ads. Some sites may not work properly.

When third party cookies are enabled, it works properly, but the following warning appears in console:
> A cookie associated with a cross-site resource at http://embed.api.video/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by dougsillars** [comment]
Fixed.
